cache: bundler
bundler_args: ""
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
script: bundle exec rake spec
